name: Nathan Davies
Title: Nathan Davies' first blog
url: http://matt.harzewski.com
description: Insert tagline here

permalink: /themes/:title/

highlighter: pygments
paginate: 20
post_assets: images
general_assets: images
bio: "Hello, I am a student at Doctor Challoners Grammar School. I have been here for nearly 1 year and I am loving it!"
email: nathan.davies@challoners.org
markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
